### ISSUE TITLE
core.print breaks some characters

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/lizard#24]
Minimal reproduction:
```py
core.print('boo\n')
```

This doesn't print "boo", but only "oo". The "b" is converted to a backspace.

- The following characters are affected: "b", "f", "n", "r" and "t".
- The problem doesn't occur without the trailing newline "\n".

Somehow these five characters are converted into their escaped counterparts backspace, form feed, new line, carriage return and tab.

**Comment by JensOgorek** [comment]
Adding more characters after the `\n` gets even funnier:
```
> core.print("boo\nbooboo")
oo
ooo"
```
```
> core.print("boo\nboobooboo")
oo
oooo"
```
```
> core.print("boo\nbooboobiibaa")
oo
ooiaa"
```
```
> core.print("boo\nbooboobiibaauu")
oo
ooiaauu"
```
```
> core.print("boo\nbooboobiibaauub")
oo
ooiaau"
```
There is something funny happening in the parser, I guess.

**Comment by JensOgorek** [comment]
It is definitely a problem how the parser handles ESCAPE CHARs
`#define ESCAPE_CHAR(c, info) ((c) == 'b' ? '\b' : (c) == 'f' ? '\f' : (c) == 'n' ? '\n' : (c) == 'r' ? '\r' : (c) == 't' ? '\t' : (c))`
in its code.

**Comment by falkoschindler** [comment]
Maybe we can reproduce it online?
https://ianh.github.io/owl/try/

**Comment by JensOgorek** [comment]
When processing escape sequences (like '\n'), the code used the original string length instead of the processed length. For example, "\n" has length 2, but should be length 1 after processing.
