### ISSUE TITLE
Correct IMU Documentation

### ISSUE THREAD

**Issue by Johannes-Thiel** [zauberzeug/lizard#26]
the values of the Imu are not called accel_x,... they are acc_x,... this schould be changed in the Doc

**Comment by falkoschindler** [comment]
Thanks, @Johannes-Thiel!
I fixed it in https://github.com/zauberzeug/lizard/commit/51ecb78503c582d122d1994b929af3abf0413b22. The website should be updated as soon as we release version 0.1.8.
